### ISSUE TITLE
Using svgPlot inside of Rmarkdown

### ISSUE THREAD

**Issue by tinyheero** [timelyportfolio/svgPanZoom#1]
Hi,

Thanks for this great R package. Been playing around with it and I am trying to get these "zoomable" svg graphics into my rmarkdown documents. But when I try to do this, I end up getting "repeated" static images. For example, I have the following rmarkdown document (test.Rmd):

    ```{r}
    library('svgPanZoom')
    library('ggplot2')
    svgPanZoom( ggplot(data.frame(x=1:10,y=1:10),aes(x=x,y=y)) + geom_line())
    ```

If I was just to run the svgPanZoom() function in my R console, then it will pop open my browser and I can zoom it no issues. But if I try to run:

    Rscript -e "rmarkdown::render('test.Rmd')"

I end up producing an html page that just has the image repeated several times. How can I get these zoomable svg to work with rmarkdown documents?

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ggplot2_1.0.0  svgPanZoom_0.1

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4  digest_0.6.8      grid_3.1.2        gtable_0.1.2
 [5] htmltools_0.2.6   htmlwidgets_0.3.2 MASS_7.3-37       munsell_0.4.2
 [9] plyr_1.8.1        proto_0.3-10      Rcpp_0.11.3       reshape2_1.4.1
[13] RJSONIO_1.3-0     scales_0.2.4      stringr_0.6.2
>
```

**Comment by timelyportfolio** [comment]
great, glad you are using.  I think this will solve your problem.

add fig.keep = "none" to your `{r fig.keep = "none"}`

**Comment by tinyheero** [comment]
Thanks. So basically we are discarding all the plots in the chunk?  I noticed that fig.cap parameter doesn't get used if `{r fig.keep = "none"}`. Anyway, we can still use the fig.cap with this method?

**Comment by timelyportfolio** [comment]
One solution for a caption would be to enclose the `svgPanZoom` object in a `tags$div`.  Would this work with some CSS styling?  The `tags` from `htmltools` work nicely with R markdown.

```
library(htmltools)
library(svgPanZoom)

tags$div(
  svgPanZoom()
  ,tag$div("my caption",style = "  ")
)
```

**Comment by timelyportfolio** [comment]
I'm going to close this as an issue probably handled best outside of `svgPanZoom` to keep the package tight and concentrated.  Let me know if you would like to reopen.
