### ISSUE TITLE
Four commas appear above plot

### ISSUE THREAD

**Issue by TomNash** [timelyportfolio/svgPanZoom#15]
Using the `svgPanZoom` function combined with `svgPanZoomOutput` in Shiny creates a strange issue, there are 4 commas appearing above the SVG.
<img width="969" alt="screen shot 2016-05-13 at 3 44 36 pm" src="https://cloud.githubusercontent.com/assets/8193065/15259867/a1641cca-1921-11e6-9f41-1b2bb2f9787a.png">

**Comment by timelyportfolio** [comment]
Did you solve this?  So happy you are using `svgPanZoom`.  Let me know if I can help.

**Comment by TomNash** [comment]
It seems to be specific to my file, trying to figure out why now. Never worked with SVG in this capacity. I ran the Shiny example provided and that looked fine.

**Comment by timelyportfolio** [comment]
I've fortunately/unfortunately done a whole lot with `svg`, so let me know if I can get you over the hump.

**Comment by timelyportfolio** [comment]
@TomNash, you will see in [lines](https://github.com/timelyportfolio/svgPanZoom/blob/master/R/svgPanZoom.R#L127-L130) that the file handling is pretty crude and assumes a plain `svg` element ready for `html`. I will circle back eventually to make this more robust.  Your `svg` contains some `doctype` (to make it valid `xml`) and some other meta information.  In the interest of your time (not sure when I will get to robustifying this), I would recommend cleaning the file before passing to `svgPanZoom`.  Here are a couple of options.

One note, I would recommend the option `viewBox = FALSE` for your application.

```
svg <- readLines('/path/to/svg.svg', warn=FALSE)
```

**if `svg` always starts on line 7

```
svg1 <- paste0(svg[-(1:6)], collapse="\n")
```

**a little more rigid**
```
svg2 <- paste0(
  svg[grep(x=svg,'(<svg.*)'):length(svg)],
  collapse = "\n"
)
```

We could go even further and use `xml2` or `XML`, but then we will need to worry about memory leaks.

**Comment by TomNash** [comment]
This is exactly what I found last night as well, glad to confirm it. And I'll check out the view box option too. Again, thank you for your time.
