### ISSUE TITLE
linetype="blank" is causing an error in stat_density2d

### ISSUE THREAD

**Issue by ghotson** [timelyportfolio/svgPanZoom#2]
Awesome package! One difficulty I'm having is that when I make my ggplot with a stat_density2d layer, svgPanZoom throws and error if I set linetype to blank.

example code:
**Works**

>p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
>svgPanZoom(p)

**Doesn't Work**

>p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),linetype="blank",geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
>svgPanZoom(p)
>Error in as.hexmode(strsplit(lty, "")[[1]]) : 
'x' cannot be coerced to class "hexmode"

**Comment by timelyportfolio** [comment]
Delighted to hear that you are using.  While `gridSVG` produces cleaner/better SVG, it does not always succesfully render.   One thing you can try is to use the `dev.svg` method.  Here is how to do it.  `SVGAnnotation` makes it a little easier but is not completely required.  Let me know if this does not work. One issue I know will come up is if you have multiple of these on one page.


```R
library(SVGAnnotation)
library(svgPanZoom)

p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),linetype="blank",geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
svgPanZoom(svgPlot(p,height = 10, width = 14))
```

**Comment by ghotson** [comment]
Hmm, the code you gave me works great, but it looks like I'm getting some
weird duplication/cutting off of my image with different data. I'm only
doing one plot, but I do have multiple groups in my stat_density2d with my
actual data. Does this cause the issue you're thinking of?

I've got print screens of being zoomed in at varying levels. The
stat_density2d seems to be correct when zooming, but the ggimage I'm
plotting on gets screwed up.

[image: Inline image 1][image: Inline image 2][image: Inline image 3]

**Comment by timelyportfolio** [comment]
For some reason, the screenshots are not showing up on my machine. The expected problem will come with text in the SVG caused by conflicting `defs` ids.

**Comment by ghotson** [comment]
Hmm, can you see them now?

**Comment by timelyportfolio** [comment]
I still don't see but could be in my end.  Let me play with it a bit and see if I can reproduce.

**Comment by timelyportfolio** [comment]
@ghotson, I think the issue might be with email.  To get pics to show up in Github issues, you'll need to copy/paste into the online editor.  Could you try that, or upload to something like imgur and send the link?  Thanks.

**Comment by ghotson** [comment]
Sure! Here's what happened when I zoomed in. Let me know if you can't reproduce it, and I can try looking into it further.

![image 2](https://cloud.githubusercontent.com/assets/4359117/6560262/3720bc62-c65f-11e4-986e-5e520dc1d91b.png)
![image 1](https://cloud.githubusercontent.com/assets/4359117/6560261/3720691a-c65f-11e4-8534-9f1cd9100ed4.png)
![image](https://cloud.githubusercontent.com/assets/4359117/6560260/37203bfc-c65f-11e4-8d97-20f4d0a20369.png)

**Comment by ghotson** [comment]
Ooh, I just tried it out in my browser instead of R studio's built in viewer, and it works without a hitch. I'll just be developing in my browser instead from now on.

Thanks again!
