### ISSUE TITLE
Incorporation into shiny app

### ISSUE THREAD

**Issue by ghotson** [timelyportfolio/svgPanZoom#3]
Hi, I'm having some difficulty incorporating this into a shiny app. I think I may be a bit over my head. When I simply call it on my output from ggplot inside of my shiny app, it doesn't seem to do anything. The image is still just a static image.

I'm guessing I'm supposed to use something like your code here in my shiny app: https://github.com/timelyportfolio/svgPanZoom/blob/master/R/svgPanZoom.R

Do you happen to have an example of how to use svgPanZoom with an interactive shiny plot? If not, could you provide some assistance/point me to some resources?

Thanks!
Guy

**Comment by ghotson** [comment]
Example code:
**works (able to pan/zoom)**

 p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
    svgPanZoom(p)

**doesn't work (plot displays, but unable to pan/zoom)**
library(shiny)
library(svgPanZoom)
runApp()

*server.R*

shinyServer(function(input, output) {
  
  output$main_plot <- renderPlot({    
    
    p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
    svgPanZoom(p)
    
  })
})

*ui.R*
shinyUI(bootstrapPage(
  

  plotOutput(outputId = "main_plot", height = "300px")  
  
))

**Comment by timelyportfolio** [comment]
Sure, great question, and since there is not an example, the answer is not obvious.  Here is how you would do it?  I'll add an example to the documentation.  Thanks again.

```R
library(shiny)
library(SVGAnnotation)
library(svgPanZoom)
library(ggplot2)

ui <- shinyUI(bootstrapPage(
  
  svgPanZoomOutput(outputId = "main_plot")
  
))

server = shinyServer(function(input, output) {
  output$main_plot <- renderSvgPanZoom({
    p <- ggplot() + geom_point(data=data.frame(faithful),aes(x=eruptions,y=waiting)) + stat_density2d(data=data.frame(faithful),aes(x=eruptions,y=waiting, alpha =..level..),geom="polygon") + scale_alpha_continuous(range=c(0.05,0.2))
    svgPanZoom(p, controlIconsEnabled = T)
  })
})
  
runApp(list(ui=ui,server=server))

```

**Comment by ghotson** [comment]
You're amazing, this worked perfectly!

**Comment by timelyportfolio** [comment]
great, let me know if you have any other issues.  Would love to see what you make :)

**Comment by caprice-j** [comment]
Thank you both for good information. My shiny project also works likes a charm.
