### ISSUE TITLE
Name of project

### ISSUE THREAD

**Issue by ariutta** [timelyportfolio/svgPanZoom#5]
Hi,

svg-pan-zoom contributor here. It's cool to see a project like yours.

One minor issue -- the name "svgPanZoom" is almost identical to "svg-pan-zoom", leading to confusion:
https://github.com/ariutta/svg-pan-zoom/issues/96

What about naming this repo something like svgPanZoomR?

**Comment by timelyportfolio** [comment]
After building something as useful as `svg-pan-zoom`, the last thing I want to do is bother you with issues related to this `htmlwidget` wrapper. While changing the package name can be done, it is not trivial.  If ok, I'll leave this open.  I watch `svg-pan-zoom` very closely.  If this happens again, I'll go through the process of changing.

Thanks so much for `svg-pan-zoom`.  I had hoped this project would help bring it the attention it deserves.

**Comment by ariutta** [comment]
No worries, it's not a big deal, and I'm glad svg-pan-zoom is getting used.

I actually just added you as a collaborator for svg-pan-zoom. If any more questions come up about your repo, you can redirect them and close the issue at svg-pan-zoom.

If you want to make any changes to the master branch of svg-pan-zoom, please make sure @bumbu or I have a chance to review. Thanks.
