### ISSUE TITLE
Out of bounds error with variable sized arrow head plotting

### ISSUE THREAD

**Issue by ghotson** [timelyportfolio/svgPanZoom#6]
Hi again! So I've got a weird error. I'm trying to plot some arrows, and I would like to scale the size of the arrow head according to a variable. 

If I make it a constant, things work fine. E.g.
````
x <- faithful[1:10,]
y <- faithful[2:11,]

arrowData = cbind(x,y)

p <- ggplot(arrowData) + geom_segment(aes(x = arrowData[,1], y=arrowData[,2],xend = arrowData[,3], yend = arrowData[,4]), 
                                      arrow = arrow(length = unit(1/5, "cm"))) 
svgPanZoom(p)
````
However, if I make the arrow head variable then it doesn't play nicely with svgPanZoom, e.g.

````
x <- faithful[1:10,]
y <- faithful[2:11,]

arrowData = cbind(x,y)

p <- ggplot(arrowData) + geom_segment(aes(x = arrowData[,1], y=arrowData[,2],xend = arrowData[,3], yend = arrowData[,4]), 
                                      arrow = arrow(length = unit(arrowData[,1]/5, "cm"))) 
print(p)
svgPanZoom(p)
````
shows fine with print(p), but svgPanZoom results in "Error in arrow[[i]] : subscript out of bounds"

Thanks!
Guy

**Comment by timelyportfolio** [comment]
Similar issues as #2.  `gridSVG` is better in many ways but unfortunately slightly less robust.  If you think you'll only be using one `svgPanZoom` in a page, you can try `SVGAnnotation::svgPlot`, which happens to be much faster and robust, but less pretty SVG and leads to namespace issues with text in multiple SVGs on a page.

To try `SVGAnnotation`, you can do this.

Install from either Bioconductor or Github
```
# bioconductor install
source("http://bioconductor.org/biocLite.R")
biocLite("SVGAnnotation")

# github install
devtools::install_github("duncantl/SVGAnnotation")
```

Then, 

```
library(ggplot2)
library(grid)  #  for arrow
library(SVGAnnotation)
library(svgPanZoom)

x <- faithful[1:10,]
y <- faithful[2:11,]

arrowData = cbind(x,y)

p <- ggplot(arrowData) + geom_segment(aes(x = arrowData[,1], y=arrowData[,2],xend = arrowData[,3], yend = arrowData[,4]), 
                                      arrow = arrow(length = unit(arrowData[,1]/5, "cm"))) 

svgPanZoom(svgPlot({print(p)}))
```


Thanks so much for using `svgPanZoom`.  Would love to see the final output if possible.

**Comment by ghotson** [comment]
That works great! I'm only doing one plot on my page, so that shouldn't be an issue. And the speed boost is definitely a plus.
